### ISSUE TITLE
Censoring random phrase 

### ISSUE THREAD

**Issue by tabitho86** [JPBBots/censorbot#29]
![D8137248-26F8-49BE-B4AE-02045C7751CC](https://user-images.githubusercontent.com/83878432/117546839-caa82980-b02c-11eb-85dc-5b7853fca09d.jpeg)
Hey,

We use the bot on our server on discord and usually it works great but for whatever reason it censored the phrase 'by frostbite etc' for no apparent reason. Also I cannot uncesor it as it's catching up the phrase.

Could you please look into this.

BR

**Comment by jpbberry** [comment]
Please use the `+ticket` command in order to report all of these phrases. Also please stick to the [support server](https://censor.bot/support) for help rather than GitHub issues.
