### ISSUE TITLE
Using globals

### ISSUE THREAD

**Issue by nanoqoi** [JPBBots/censorbot#40]
JS globals bad, should be passed as props or use a provider and content instead

https://github.com/JPBBots/censorbot/blob/dd95aaa5cee7642f011b00411e3634a3b4185f15/website/src/pages/_app.tsx#L23

**Comment by jpbberry** [comment]
This is only done for easily debugging from the console, this will likely be a staging-only thing as well. In actual code it is
```js
import { api } from '_app.ts'
```
