### ISSUE TITLE
Question: Can I get access to the filter data?

### ISSUE THREAD

**Issue by WillTDA** [JPBBots/censorbot#43]
From what I can see, the filter gets some of its data from `bot/src/data/filter`. Can I get access to that?

**Comment by jpbberry** [comment]
The base filter is intentionally ignored in order to stop blatant copying of Censor Bot as the rest of it is open source. The base filter is basically the secret sauce behind the public version of Censor Bot.

**Comment by WillTDA** [comment]
Got it, thanks for the quick response 👍
